### ISSUE TITLE
Setting width on resourceColumns does nothing

### ISSUE THREAD

**Issue by micobarac** [fullcalendar/fullcalendar-scheduler#511]
### Bug Reports
Setting width on resourceColumns does nothing.

```javascript
document.addEventListener('DOMContentLoaded', function() {
  var calendarEl = document.getElementById('calendar');

  var calendar = new FullCalendar.Calendar(calendarEl, {
    plugins: [ 'resourceTimeline' ],
    header: {
      left: 'today prev,next',
      center: 'title',
      right: 'resourceTimelineDay,resourceTimelineWeek'
    },
    defaultView: 'resourceTimelineDay',
    resourceColumns: [
      {
        labelText: 'Room',
        field: 'title',
        width: '50px'
      },
      {
        labelText: 'Occupancy',
        field: 'occupancy',
        width: '2rem'
      }
    ],
    resources: [
      { id: 'a', title: 'Auditorium A', occupancy: 40 },
      { id: 'b', title: 'Auditorium B', occupancy: 60 },
      { id: 'c', title: 'Auditorium C', occupancy: 40 },
      { id: 'd', title: 'Auditorium D', occupancy: 40 },
      { id: 'e', title: 'Auditorium E', occupancy: 60 },
      { id: 'f', title: 'Auditorium F', occupancy: 60 },
      { id: 'g', title: 'Auditorium G', occupancy: 60 },
      { id: 'h', title: 'Auditorium H', occupancy: 40 },
      { id: 'i', title: 'Auditorium I', occupancy: 70 },
      { id: 'j', title: 'Auditorium J', occupancy: 70 },
      { id: 'k', title: 'Auditorium K', occupancy: 70 },
      { id: 'l', title: 'Auditorium L', occupancy: 75 },
      { id: 'm', title: 'Auditorium M', occupancy: 40 },
      { id: 'n', title: 'Auditorium N', occupancy: 40 },
      { id: 'o', title: 'Auditorium O', occupancy: 40 },
      { id: 'p', title: 'Auditorium P', occupancy: 40 },
      { id: 'q', title: 'Auditorium Q', occupancy: 40 },
      { id: 'r', title: 'Auditorium R', occupancy: 40 },
      { id: 's', title: 'Auditorium S', occupancy: 40 },
      { id: 't', title: 'Auditorium T', occupancy: 40 },
      { id: 'u', title: 'Auditorium U', occupancy: 40 },
      { id: 'v', title: 'Auditorium V', occupancy: 40 },
      { id: 'w', title: 'Auditorium W', occupancy: 40 },
      { id: 'x', title: 'Auditorium X', occupancy: 40 },
      { id: 'y', title: 'Auditorium Y', occupancy: 40 },
      { id: 'z', title: 'Auditorium Z', occupancy: 40 }
    ]
  });

  calendar.render();
});
```

**Comment by acerix** [comment]
Confirmed, thanks for the demo

https://codepen.io/acerix/pen/LaXBbb?editors=0010

**Comment by micobarac** [comment]
Current workaround is to set width though CSS:

```scss
.fc-ltr .fc-resource-area tr:not(.fc-super) > {
  & * {
    text-align: center;
  }

  th:first-child > *,
  td:first-child > * {
    text-align: left;
  }
}
```

**Comment by arshaw** [comment]
fixed in [v4.0.2](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v4.0.2)!

**Comment by innoveltec** [comment]
setting the width of the resource columns still does nothing. Using the premium resource timeline in angular. Using version 4.3.0.

**Comment by razorhenry1** [comment]
> fixed in [v4.0.2](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v4.0.2)!

It's still not working in version 4.3.0

**Comment by thepoho** [comment]
As far as I can tell, this only works when setting an integer: `width: 20`,  instead of a string:`width: '20'`.  I believe they are the percentage.
Can confirm that setting it to a string with px or % in it doesn't work in `4.4.0`.
